[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "openai>=2.15.0",
    "tiktoken>=0.12.0",
    "fastapi[standard]>=0.115.6",
    "uvicorn[standard]>=0.32.0",
    "sse-starlette>=2.1.3",
]
